/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LettersSpaceDotTextFieldKeyListener1;
import Controller.NumericTextFieldKeyListener1;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Model.Dbconnection;
import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import Controller.LettersSpaceDotTextFieldKeyListener1;

/**
 *
 * @author Dell
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("BookID");
        tableModel.addColumn("StudentID");
        tableModel.addColumn("Issue Book");
        tableModel.addColumn("Due Date");
        issueList.setModel(tableModel);

        // Fetch and display existing car data from the database
        displayExistingIssueBookData();
        txtIssuebookID.addKeyListener(new NumericTextFieldKeyListener1());
        txtIssuestudentID.addKeyListener(new LettersSpaceDotTextFieldKeyListener1());
        txtIssuebook.addKeyListener(new LettersSpaceDotTextFieldKeyListener1());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIssuebookID = new javax.swing.JTextField();
        txtIssuestudentID = new javax.swing.JTextField();
        txtIssuebook = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueList = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        duedateSelector = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Issue Book");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Due Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtIssuebookID.setBackground(new java.awt.Color(255, 255, 204));
        txtIssuebookID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIssuebookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssuebookIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtIssuebookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 196, -1));

        txtIssuestudentID.setBackground(new java.awt.Color(255, 255, 204));
        txtIssuestudentID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtIssuestudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 196, -1));

        txtIssuebook.setBackground(new java.awt.Color(255, 255, 204));
        txtIssuebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtIssuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 196, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        issueList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Student ID ", "Issue Book", "Due Date"
            }
        ));
        jScrollPane1.setViewportView(issueList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 610, 190));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        duedateSelector.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(duedateSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/dis.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
     private void saveIssueBookToDatabase() {
    String book_id = txtIssuebookID.getText();     
    String Student_Id = txtIssuestudentID.getText();
    String IssueBook=  txtIssuebook.getText();
     Date DueDate = duedateSelector.getDate(); 
    
    

    try {
        try ( // Establish a database connection
                 Connection connection = Dbconnection.getConnection();){
            String sql = "INSERT INTO IssueBook(IssueBook_ID,Book_ID, Student_ID, IssueBook, Due_Date) VALUES (?, ?, ?, ?,?)";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, book_id );
             preparedStatement.setString(2, Student_Id);
            preparedStatement.setString(4, IssueBook);
          preparedStatement.setDate(3, new java.sql.Date(DueDate.getTime()));
          
            
            
            int rowsAffected = preparedStatement.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Book issued successfully.");
                // Clear the input fields after successful insertion
               txtIssuebookID.setText(""); 
                txtIssuestudentID.setText("");
                txtIssuebook.setText("");
                 duedateSelector.setDate(null);// Reset to the first status option
                
              
                
                DefaultTableModel tableModel = (DefaultTableModel) issueList.getModel();
            tableModel.addRow(new Object[]{book_id,Student_Id,IssueBook,DueDate});
            } else {
                JOptionPane.showMessageDialog(this, "Failed to issue book.");
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = issueList.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this issued books details?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                DefaultTableModel tableModel = (DefaultTableModel) issueList.getModel();

                // Get the carRegistration value from the selected row
                String bookID = (String) tableModel.getValueAt(selectedRow, 0);
                // Remove the selected row from the table
                tableModel.removeRow(selectedRow);

                try {
                    try ( // Establish a database connection
                        Connection connection = Dbconnection.getConnection();  )    {
                        String sql = "DELETE FROM IssueBook WHERE IssueBook_ID";

                        PreparedStatement preparedStatement = connection.prepareStatement(sql);
                        preparedStatement.setString(1, bookID);

                        int rowsAffected = preparedStatement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "issued books details deleted successfully.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to delete issued books details from the database.");
                        }
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select issued books details to delete.");
        }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIssuebookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssuebookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssuebookIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = issueList.getSelectedRow();
        if (selectedRow != -1) {
            // Get the updated data from the text fields and combo box
            String updatedBook_ID = txtIssuebookID.getText();
            String updatedStudendId= txtIssuestudentID.getText();
            String updatedIssuebook =txtIssuebook.getText();
             Date updatedDuedate = duedateSelector.getDate();
           

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the issued book?", "Confirm Update", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Update the data in the table (user interface)
                DefaultTableModel tableModel = (DefaultTableModel) issueList.getModel();
                tableModel.setValueAt(updatedBook_ID, selectedRow, 0);
                tableModel.setValueAt(updatedStudendId, selectedRow, 1);
                tableModel.setValueAt(updatedIssuebook, selectedRow, 2);
                tableModel.setValueAt(updatedDuedate, selectedRow, 3);
                

                // Update the data in the MySQL table
                try {
                    // Establish a database connection
                    Connection connection = Dbconnection.getConnection();

                    // Define the SQL query to update the record in the database
                    String sql = "UPDATE IssueBook SET Book_ID= ? Student_ID =?, IssueBook=?, Due_Date=? WHERE IssueBook_ID ";

                    // Prepare the statement
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1, updatedIssuebook);
                   
                    preparedStatement.setDate(2, new java.sql.Date(updatedDuedate.getTime()));
                    preparedStatement.setString(3, updatedBook_ID);
                    preparedStatement.setString(4, updatedStudendId);

                    // Execute the update
                    int rowsAffected = preparedStatement.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Issued books updated successfully.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to update issued books details in the database.");
                    }

                    // Close the database connection
                    connection.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select issued books details to update.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         saveIssueBookToDatabase();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void displayExistingIssueBookData() {
    try {
        try ( // Establish a database connection
              Connection connection = Dbconnection.getConnection();) {
            String sql = "SELECT IssueBook_ID,Book_ID, Student_ID, IssueBook, Due_Date  FROM IssueBook";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            
            DefaultTableModel tableModel = (DefaultTableModel) issueList.getModel();
            
            while (resultSet.next()) {
                String BookID = resultSet.getString("BookID");
                String StudentID = resultSet.getString("StudentID");
                String IssueBook = resultSet.getString("IssueBook");
                Date DueDate = resultSet.getDate("DueDate");
                
                // Add the fetched data as a new row in the table
                tableModel.addRow(new Object[]{BookID, StudentID, IssueBook, DueDate});
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser duedateSelector;
    private javax.swing.JTable issueList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIssuebook;
    private javax.swing.JTextField txtIssuebookID;
    private javax.swing.JTextField txtIssuestudentID;
    // End of variables declaration//GEN-END:variables
}
